import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

import { AuthProvider } from '@/lib/AuthContext';
import { NavbarProvider } from '@/lib/NavbarContext';
import { RewardProvider } from '@/lib/RewardContext';
import { Toaster } from 'react-hot-toast';
import Navbar from '@/components/navbar';
import MainLayout from '@/components/MainLayout';
import Footer from '@/components/Footer';
//import ChatInterface from "@/components/ChatInterface"; 
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <RewardProvider>
            <NavbarProvider>
              <Toaster position="top-center" />
              <Navbar />
              <MainLayout>
                {children}
              </MainLayout>
              <Footer />
            </NavbarProvider>
          </RewardProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
